default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: mysql

development:
  <<: *default
  database: co-note_development

test:
  <<: *default
  database: co-note_test

production:
  <<: *default
  database: co-note_production
  username: co-note
  password: <%= ENV['CO-NOTE_DATABASE_PASSWORD'] %>
